services:
  - type: web
    name: n8n-automation
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        generateValue: true
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: N8N_HOST
        value: n8n-automation-hea4.onrender.com
      - key: N8N_PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-automation-hea4.onrender.com
      - key: GENERIC_TIMEZONE
        value: America/Santiago
      - key: DB_TYPE
        value: sqlite
      - key: DB_SQLITE_DATABASE
        value: /opt/render/project/src/.n8n/database.sqlite
      - key: NODE_ENV
        value: production
